config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "portfolio#index"
  resources :profile, only: [:index]
  resources :users, only: [:show]
  resources :works, only: [:index, :show, :new, :create]
  resources :blogs, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  get "/blogs", to:  "blogs#top"
  post "/like/:blog_id" => "likes#like", as: 'like'
  delete '/like/:blog_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :comments
  validates :images, :text, :title, presence: true
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  
  def self.search(search)
    return Blog.all unless search
    Blog.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blog, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :blogs
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_blogs, through: :likes, source: :blog
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  has_one_attached :work_image
  validates :work_image, :name, :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def top
    @blogs = Blog.with_attached_images.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    end
    
    def new
    @blog = Blog.new
    end
    
    def create
    Blog.create(blog_params)
    redirect_to blogs_path
    end

    def show
      @blog = Blog.find(params[:id])
      @comment = Comment.new
      @comments = @blog.comments.includes(:user)
    end

    def edit
      if current_user.admin?
        @blog = Blog.find(params[:id])
      else
        redirect_to blog_path
      end
    end

    def update
      blog = Blog.find(params[:id])
      blog.update(blog_params)
      redirect_to blog_path(blog.id)
    end

    def destroy
      if user_signed_in? && current_user.admin? && current_user.id == @blog.user.id
        blog = Blog.find(params[:id])
        blog.destroy
        redirect_to blogs_path
      else
        redirect_to blogs_path
      end
    end

    def search
      @blogs = Blog.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(5)
    end
    
    private
    def blog_params
    params.require(:blog).permit(:title, :text, images: []).merge(user_id: current_user.id)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/blogs/#{comment.blog.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, blog_id: params[:blog_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(blog_id: @blog.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(blog_id: @blog.id)
    like.destroy
  end

  private
  def set_variables
    @blog = Blog.find(params[:blog_id])
    @id_name = "#like-link-#{@blog.id}"
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def index
    @works = Work.all
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.id == params[:id].to_i
      user = User.find_by(id: params[:id])
      @blogs = Like.where(user_id: user.id)
    else
      redirect_to root_path
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    Work.create(work_params)
    redirect_to blogs_path
  end

  private
  def work_params
    params.require(:work).permit(:name, :url, images: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/blogs/_blog.html.haml
.blog_contents
  = link_to blog_path(blog.id) do
    .blog_contents_box
      .blog_contents_box_fix
        %p
          = blog.title
        %p
          = blog.created_at.strftime("%Y-%m-%d %H:%M")
      .blog_contents_box_top
        %figure.blog_contents_box_top_figure
          = image_tag(blog.images[0], size: "75%x75%", class: "img")
          %figcaption.figcaption
            %p
              = blog.title
      .blog_contents_box_bottom
        .blog_contents_box_bottom_text
          %span
            = blog.text
      - if user_signed_in?
        = render 'likes/like', blog: blog

app/views/blogs/edit.html.haml
.my_area
  .form
    = form_with(model: @blog, local: true) do |f|
      .form_title
        = f.text_field :title, placeholder: "title"
      .form_text
        = f.text_area :text, placeholder: "text"
      .form_imgae
        = f.label :images, for: 'up_images' do
          = f.file_field :images,id: 'up_images', multiple: true, name: 'blog[images][]', placeholder: "image"
      .form_submit
        = f.submit '編集する'

app/views/blogs/new.html.haml
//管理者のみの投稿フォーム
.my_area
  .form
    = form_with(model: @blog, local: true) do |f|
      .form_title
        = f.text_field :title, placeholder: "title"
      .form_text
        = f.text_area :text, placeholder: "text"
      .form_imgae
        = f.label :images, for: 'up_images' do
          = f.file_field :images,id: 'up_images', multiple: true, name: 'blog[images][]', placeholder: "image"
      .form_submit
        = f.submit '投稿する'

app/views/blogs/search.html.haml
%main.blog_warraper
  .blog_warraper_box
    .blog_warraper_box_left
      = link_to "Blog", blogs_path, class: "link"
    = form_with(url: search_blogs_path, local: true, method: :get) do |f|
      = f.text_field :keyword, placeholder: "投稿検索", class: "field"
      = f.submit "検索"
    .blog_warraper_box_right
      -if (user_signed_in? && current_user.admin?)
        = link_to '投稿ページ', new_blog_path, class: "link"
      - if user_signed_in?
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "link"
      - else
        = link_to 'ログイン', new_user_session_path, class: "link"
        = link_to '新規登録', new_user_registration_path, class: "link"
  = render @blogs
  = paginate @blogs
.footer
  = link_to '#top' do
    = icon "fa", "arrow-alt-circle-up",class: "arrow"

app/views/blogs/show.html.haml
= render 'shade/header'
%main.blog_warraper
  .blog_contents
    .blog_contents_box
      .blog_contents_box_top
        %p
          = @blog.title
        %figure.blog_contents_box_top_figure
          - @blog.images.each do |image|
            = image_tag(image, size: "75%x75%", class: "img")
      .blog_contents_box_bottom
        .blog_contents_box_bottom_text
          %span
            = @blog.text
      - if user_signed_in?
        = render 'likes/like', blog: @blog
-if (user_signed_in? && current_user.admin? && current_user.id == @blog.user.id)
  %br
  %br
  .my_edit
    = link_to "編集する",  edit_blog_path(@blog.id)
  %br
  .my_delete
    = link_to "削除する", "/blogs/#{@blog.id}", method: :delete
  .comment_area
    -if current_user
      = form_with(model: [@blog, @comment], local: true) do |f|
        = f.text_area :text, placeholder: "コメント", rows: "2"
        = f.submit "送信"
  .comments
    .top
      コメント一覧
    - if @comments
      - @comments.each do |comment|
        .comments_deteil
          .comments_deteil_nickname
            = comment.user.nickname
          .comments_deteil_text
            = comment.text

app/views/blogs/top.html.haml
%header.blog_header#top
  = render 'shade/header'
%main.blog_warraper
  .blog_warraper_box
    .blog_warraper_box_left
      = link_to "Blog", blogs_path, class: "link"
    = form_with(url: search_blogs_path, local: true, method: :get) do |f|
      = f.text_field :keyword, placeholder: "投稿検索", class: "field"
      = f.submit "検索"
    .blog_warraper_box_right
      -if (user_signed_in? && current_user.admin?)
        = link_to '投稿ページ', new_blog_path, class: "link"
      - if user_signed_in?
        = link_to 'マイページ', "/users/#{current_user.id}", class: "link"
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "link"
      - else
        = link_to 'ログイン', new_user_session_path, class: "link"
        = link_to '新規登録', new_user_registration_path, class: "link"
  = render @blogs
  = paginate @blogs
.footer
  = link_to '#top' do
    = icon "fa", "arrow-alt-circle-up",class: "arrow"

app/views/likes/_like.html.haml
.like-link{:id => "like-link-#{blog.id}"}
  - if current_user.likes.find_by(blog_id: blog.id)
    = link_to unlike_path(blog.id), method: :delete, remote: true do
      .iine__button
        ❤️#{blog.likes.count}
  - else
    = link_to like_path(blog.id), method: :post, remote: true do
      .iine__button
        ♡️#{blog.likes.count}

app/views/likes/like.js.haml
$("#{@id_name}").html('#{escape_javascript(render("likes/like", blog: @blog  ))}');

app/views/likes/unlike.js.haml
$("#{@id_name}").html('#{escape_javascript(render("likes/like", blog: @blog  ))}');

app/views/portfolio/index.html.haml
%header.header#top
  = render 'shade/header'
%main.contents
  .contents_first#Top
    .contents_first_warrap
      .contents_first_warrap_mask
        .boxs
          .boxs_title
            Portfolio
          .boxs_comment
            %p
              初学者から学習を行いRuby on Rails を利用しアプリケーションの開発を行なっています
          .boxs_introduction
            %ul.boxs_introduction_box
              学習中の内容
              %li Ruby on Rails
              %li mysql
              %li kotlin
          .boxs_about
            = link_to 'about', profile_index_path , class: "link"
  = render 'shade/works', collection: :@works

app/views/users/show.html.haml
.my_page
  .my_page_top
    .my_page_top
      マイページ
%main.blog_warraper
  .blog_contents
    -@blogs.each do |blog|
      = link_to blog_path(blog.blog.id) do
        .blog_contents_box
          .blog_contents_box_fix
            %p
              = blog.blog.title
            %p
              = blog.created_at.strftime("%Y-%m-%d %H:%M")
          .blog_contents_box_top
            %figure.blog_contents_box_top_figure
              = image_tag(blog.blog.images[0], size: "75%x75%", class: "img")
              %figcaption.figcaption
                %p
                  = blog.blog.title
          .blog_contents_box_bottom
            .blog_contents_box_bottom_text
              %span
                = blog.blog.text
          - if user_signed_in?
            = render 'likes/like', blog: blog.blog

app/views/works/index.html.haml
= render 'shade/header'
- if current_user.admin?
  .work_add
    = link_to 'アプリの追加', work_path(@work.id)
= render 'shade/works', collection: :@works

app/views/works/show.html.haml
= @work.name