config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "portfolio#index"
  resources :profile, only: [:index]
  resources :users, only: [:show]
  resources :works, only: [:index, :show, :new, :create]
  resources :blogs, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  get "/blogs", to:  "blogs#top"
  post "/like/:blog_id" => "likes#like", as: 'like'
  delete '/like/:blog_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :comments
  validates :images, :text, :title, presence: true
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  
  def self.search(search)
    return Blog.all unless search
    Blog.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blog, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :blogs
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_blogs, through: :likes, source: :blog
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  has_one_attached :work_image
  validates :work_image, :name, :url, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def top
    @blogs = Blog.with_attached_images.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    end
    
    def new
    @blog = Blog.new
    end
    
    def create
    Blog.create(blog_params)
    redirect_to blogs_path
    end

    def show
      @blog = Blog.find(params[:id])
      @comment = Comment.new
      @comments = @blog.comments.includes(:user)
    end

    def edit
      if current_user.admin?
        @blog = Blog.find(params[:id])
      else
        redirect_to blog_path
      end
    end

    def update
      blog = Blog.find(params[:id])
      blog.update(blog_params)
      redirect_to blog_path(blog.id)
    end

    def destroy
      if user_signed_in? && current_user.admin? && current_user.id == @blog.user.id
        blog = Blog.find(params[:id])
        blog.destroy
        redirect_to blogs_path
      else
        redirect_to blogs_path
      end
    end

    def search
      @blogs = Blog.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(5)
    end
    
    private
    def blog_params
    params.require(:blog).permit(:title, :text, images: []).merge(user_id: current_user.id)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/blogs/#{comment.blog.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, blog_id: params[:blog_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(blog_id: @blog.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(blog_id: @blog.id)
    like.destroy
  end

  private
  def set_variables
    @blog = Blog.find(params[:blog_id])
    @id_name = "#like-link-#{@blog.id}"
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.id == params[:id].to_i
      user = User.find_by(id: params[:id])
      @blogs = Like.where(user_id: user.id)
    else
      redirect_to root_path
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    Work.create(work_params)
    redirect_to blogs_path
  end

  private
  def work_params
    params.require(:work).permit(:name, :url, images: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HtmlReview
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/shade/_header.html.haml
.header_warrap
  .left
    .left_top
      = link_to '/' do
        = icon 'fa', 'home', class: "home"
  .center
    %ul.center_ul
      %li.center_ul_li
        =link_to 'Profile', profile_index_path ,class: "link"
      %li.center_ul_li
        = link_to 'Blog', blogs_path ,class: "link"
      %li.center_ul_li
        = link_to 'MyWorks', works_path,class: "link"
      %li.center_ul_li
        = link_to 'Contact', '/',class: "link"
  .right
    .right_icon
      = link_to 'https://twitter.com/HbFOFW7rtnIfyY6' do
        = icon 'fab', 'twitter',class: "twitter"

app/views/shade/_works.html.haml
.contents_second#Profile
  .contents_second_warrap
    .box_warrap
      .box
        %p
          Works
      - @works.each do |work|
        %ul.items
          %li.items_app
            = link_to work_path(work.id), class: "link" do
              .items_app_header
                %figure.items_app_header_figure
                  = image_tag("images/point_app",size:'280x260')
              .items_app_footer
                = work.name
      - if request.path_info == root_path
        .work_more
          = link_to 'more', works_path, class: "link"